# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Development/School/computer_arch/cpu_project/nexys-a7/nexys-a7.srcs/sources_1/ip/block_mem_data/block_mem_data.xci
# IP: The module: 'block_mem_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Development/School/computer_arch/cpu_project/nexys-a7/nexys-a7.gen/sources_1/ip/block_mem_data/block_mem_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_mem_data'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Development/School/computer_arch/cpu_project/nexys-a7/nexys-a7.srcs/sources_1/ip/block_mem_data/block_mem_data.xci
# IP: The module: 'block_mem_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Development/School/computer_arch/cpu_project/nexys-a7/nexys-a7.gen/sources_1/ip/block_mem_data/block_mem_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_mem_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
