# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Development/School/computer_arch/cpu_project/nexys-a7/nexys-a7.srcs/sources_1/ip/clk_64_mhz/clk_64_mhz.xci
# IP: The module: 'clk_64_mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Development/School/computer_arch/cpu_project/nexys-a7/nexys-a7.gen/sources_1/ip/clk_64_mhz/clk_64_mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_64_mhz'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Development/School/computer_arch/cpu_project/nexys-a7/nexys-a7.gen/sources_1/ip/clk_64_mhz/clk_64_mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_64_mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Development/School/computer_arch/cpu_project/nexys-a7/nexys-a7.gen/sources_1/ip/clk_64_mhz/clk_64_mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_64_mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Development/School/computer_arch/cpu_project/nexys-a7/nexys-a7.srcs/sources_1/ip/clk_64_mhz/clk_64_mhz.xci
# IP: The module: 'clk_64_mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Development/School/computer_arch/cpu_project/nexys-a7/nexys-a7.gen/sources_1/ip/clk_64_mhz/clk_64_mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_64_mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Development/School/computer_arch/cpu_project/nexys-a7/nexys-a7.gen/sources_1/ip/clk_64_mhz/clk_64_mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_64_mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Development/School/computer_arch/cpu_project/nexys-a7/nexys-a7.gen/sources_1/ip/clk_64_mhz/clk_64_mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_64_mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
