set_property SRC_FILE_INFO {cfile:d:/Development/School/computer_arch/cpu_project/nexys-a7/nexys-a7.gen/sources_1/ip/clk_64_mhz/clk_64_mhz/clk_64_mhz_in_context.xdc rfile:../../../../../nexys-a7.gen/sources_1/ip/clk_64_mhz/clk_64_mhz/clk_64_mhz_in_context.xdc id:1 order:EARLY scoped_inst:clk_64} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Development/School/computer_arch/cpu_project/nexys-a7/nexys-a7.srcs/constrs_1/imports/digital_systems/Nexys-A7-100T-Master.xdc rfile:../../../../../nexys-a7.srcs/constrs_1/imports/digital_systems/Nexys-A7-100T-Master.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name CLK100MHZ [get_ports CLK100MHZ]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_64/clk_out1 -source [get_pins clk_64/clk_in1] -edges {1 2 3} -edge_shift {0.000 2.812 5.625} [get_pins clk_64/clk_out1]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports CLK100MHZ]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports CLK100MHZ]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells clk_64]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports CLK100MHZ]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells clk_64]
